databaseChangeLog:
  - changeSet:
      id: gc_add_BasicConfigManager_to_nb_authority
      author: Guozhang Luo
      comment: add BasicConfigManager to nb_authority
      dbms: oracle
      changes:
        - sqlFile:
            encoding: utf8
            relativeToChangelogFile: true
            path: sqlfile/insert_BasicConfigManager_to_nb_authority.sql