databaseChangeLog:
  - changeSet:
      id: create-GC_FUTURE_HOLD_CONFIG-table
      author: Naferian Wang
      comment: Create table GC_FUTURE_HOLD_CONFIG
      changes:
        - createTable:
            tableName: GC_FUTURE_HOLD_CONFIG
            remarks: lotId holdInfo
            columns:
              - column:
                  name: OBJECT_RRN
                  type: bigint
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
                  remarks: 主键
              - column:
                  name: ACTIVE_FLAG
                  type: varchar(1)
                  defaultValue: Y
                  remarks: 数据是否可用
              - column:
                  name: ORG_RRN
                  type: bigint
                  defaultValueNumeric: 0
                  remarks: 区域号
              - column:
                  name: CREATED
                  type: datetime
                  defaultValueComputed: CURRENT_TIMESTAMP
                  remarks: 创建时间
              - column:
                  name: CREATED_BY
                  type: varchar(32)
                  remarks: 创建者
              - column:
                  name: UPDATED
                  type: datetime
                  defaultValueComputed: CURRENT_TIMESTAMP
                  remarks: 更新时间
              - column:
                  name: UPDATED_BY
                  type: varchar(32)
                  remarks: 更新者
              - column:
                  name: LOCK_VERSION
                  type: bigint
                  defaultValueNumeric: 1
                  remarks: 乐观锁版本 程序自己更新 不可人为改变
              - column:
                  name: LOT_ID
                  type: varchar(64)
                  remarks: lotId
              - column:
                  name: HOLD_REASON
                  type: varchar(64)
                  remarks: HOLD原因
  - changeSet:
      id: add-unique-constraint-for-GC_FUTURE_HOLD_CONFIG-table
      author: Guozhang Luo
      comment: Apply unique constraint (LOT_ID) for GC_FUTURE_HOLD_CONFIG
      changes:
        - addUniqueConstraint:
            tableName: GC_FUTURE_HOLD_CONFIG
            columnNames: LOT_ID
            constraintName: UK_LOT_ID